name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  dockerCI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.USER_NAME }}/aplikacja-webowa:latest
          ${{ secrets.USER_NAME }}/aplikacja-webowa:1.0

  kubernetesCI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Config repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.USER_NAME }}/Config-repo
          path: Config-repo

      - name: Update manifests in Config repo
        run: |
          sed -i 's|image: aplikacja-webowa:1.0|image: ${{ secrets.USER_NAME }}/aplikacja-webowa:1.0|' Config-repo/deployment.yaml
          git -C Config-repo config user.name "${{ secrets.USER_NAME }}"
          git -C Config-repo config user.email "${{ secrets.USER_NAME }}@gmail.com"
          git -C Config-repo add deployment.yaml
          git -C Config-repo commit -m "Update image in deployment.yaml"
          git -C Config-repo push https://${{ secrets.TOKEN }}@github.com/${{ secrets.USER_NAME }}/Config-repo.git
